<a href="https://colab.research.google.com/github/santiagonajera/SQL_Python_Bases/blob/main/SQL-pt2-16junio2026.ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install sqlite3

ERROR: Could not find a version that satisfies the requirement sqlite3 (from versions: none)
ERROR: No matching distribution found for sqlite3

In [2]:
# Paso 1: Importar bibliotecas
import pandas as pd
import sqlite3
from sqlalchemy import create_engine

In [3]:
# Paso 2: Descargar los archivos CSV desde GitHub
import requests

base_url = "https://raw.githubusercontent.com/santiagonajera/SQL_Python_Bases/main/Datos/"

csv_files = [
    "customers.csv",
    "employees.csv",
    "orders.csv",
    "productcategories.csv",
    "products.csv",
    "products_subcategories.csv",
    "vendor_products.csv",
    "vendors.csv"
]

for file in csv_files:
    url = base_url + file
    response = requests.get(url)
    with open(file, "wb") as f:
        f.write(response.content)
    print(f"Descargado: {file}")

Descargado: customers.csv
Descargado: employees.csv
Descargado: orders.csv
Descargado: productcategories.csv
Descargado: products.csv
Descargado: products_subcategories.csv
Descargado: vendor_products.csv
Descargado: vendors.csv

In [4]:
# Paso 3: Crear una base de datos SQLite en memoria
engine = create_engine('sqlite:///:memory:')
conn = engine.connect()

In [5]:
# Paso 3: Crear una base de datos SQLite en memoria
engine = create_engine('sqlite:///:memory:')
conn = engine.connect()

In [8]:
# Paso 5: Ejecutar una consulta de ejemplo
query = """
SELECT * FROM customers LIMIT 5;
"""

result = pd.read_sql_query(query, engine)
print("Primeros 5 clientes:")
display(result)

OperationalError: (sqlite3.OperationalError) no such table: customers
[SQL:
SELECT * FROM customers LIMIT 5;
]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [9]:
import os
print(os.listdir())

['.config', 'products.csv', 'employees.csv', 'customers.csv', 'orders.csv', 'productcategories.csv', 'products_subcategories.csv', 'vendor_products.csv', 'vendors.csv', 'sample_data']

In [10]:
import pandas as pd
import requests

base_url = "https://raw.githubusercontent.com/santiagonajera/SQL_Python_Bases/main/Datos/"

csv_files = [
    "customers.csv",
    "employees.csv",
    "orders.csv",
    "productcategories.csv",
    "products.csv",
    "products_subcategories.csv",
    "vendor_products.csv",
    "vendors.csv"
]

for file in csv_files:
    url = base_url + file
    try:
        df = pd.read_csv(url)
        df.to_csv(file, index=False)
        print(f"✅ {file} - Descargado y guardado con éxito. Registros: {len(df)}")
    except Exception as e:
        print(f"❌ Error descargando {file}: {e}")

❌ Error descargando customers.csv: 'utf-8' codec can't decode byte 0xe7 in position 8900: invalid continuation byte
❌ Error descargando employees.csv: 'utf-8' codec can't decode byte 0xe9 in position 857: invalid continuation byte
✅ orders.csv - Descargado y guardado con éxito. Registros: 60919
✅ productcategories.csv - Descargado y guardado con éxito. Registros: 4
✅ products.csv - Descargado y guardado con éxito. Registros: 295
❌ Error descargando products_subcategories.csv: HTTP Error 404: Not Found
❌ Error descargando vendor_products.csv: HTTP Error 404: Not Found
✅ vendors.csv - Descargado y guardado con éxito. Registros: 104

In [11]:
import pandas as pd
import requests

base_url = "https://raw.githubusercontent.com/santiagonajera/SQL_Python_Bases/main/Datos/"

csv_files = [
    "customers.csv",
    "employees.csv",
    "orders.csv",
    "productcategories.csv",
    "products.csv",
    "products_subcategories.csv",
    "vendor_products.csv",
    "vendors.csv"
]

# Archivos que necesitan codificación especial
encoding_map = {
    "customers.csv": "latin1",
    "employees.csv": "latin1",
}

for file in csv_files:
    url = base_url + file
    try:
        # Si el archivo necesita codificación específica, la usamos
        codif = encoding_map.get(file, "utf-8")
        df = pd.read_csv(url, encoding=codif)
        df.to_csv(file, index=False)
        print(f"✅ {file} - Descargado y guardado con éxito. Registros: {len(df)}")
    except Exception as e:
        print(f"❌ Error descargando {file}: {e}")

✅ customers.csv - Descargado y guardado con éxito. Registros: 635
✅ employees.csv - Descargado y guardado con éxito. Registros: 17
✅ orders.csv - Descargado y guardado con éxito. Registros: 60919
✅ productcategories.csv - Descargado y guardado con éxito. Registros: 4
✅ products.csv - Descargado y guardado con éxito. Registros: 295
❌ Error descargando products_subcategories.csv: HTTP Error 404: Not Found
❌ Error descargando vendor_products.csv: HTTP Error 404: Not Found
✅ vendors.csv - Descargado y guardado con éxito. Registros: 104

In [12]:
from sqlalchemy import create_engine
import pandas as pd

# Crear una base de datos SQLite en memoria
engine = create_engine('sqlite:///:memory:')

# Lista de archivos CSV descargados correctamente
csv_files = [
    "customers.csv",
    "employees.csv",
    "orders.csv",
    "productcategories.csv",
    "products.csv",
    "vendors.csv"
]

# Cargar cada archivo como una tabla en la base de datos
for file in csv_files:
    table_name = file.split(".")[0]  # Nombre de la tabla será el nombre del archivo sin .csv
    try:
        df = pd.read_csv(file)
        df.to_sql(table_name, engine, if_exists='replace', index=False)
        print(f"✅ Tabla '{table_name}' creada con éxito. Columnas: {list(df.columns)}")
    except Exception as e:
        print(f"❌ Error al cargar '{table_name}': {e}")

✅ Tabla 'customers' creada con éxito. Columnas: ['CustomerID', 'FirstName', 'LastName', 'FullName']
✅ Tabla 'employees' creada con éxito. Columnas: ['EmployeeID', 'ManagerID', 'FirstName', 'LastName', 'FullName', 'JobTitle', 'OrganizationLevel', 'MaritalStatus', 'Gender', 'Territory', 'Country', 'Group']
✅ Tabla 'orders' creada con éxito. Columnas: ['SalesOrderID', 'SalesOrderDetailID', 'OrderDate', 'DueDate', 'ShipDate', 'EmployeeID', 'CustomerID', 'SubTotal', 'TaxAmt', 'Freight', 'TotalDue', 'ProductID', 'OrderQty', 'UnitPrice', 'UnitPriceDiscount', 'LineTotal']
✅ Tabla 'productcategories' creada con éxito. Columnas: ['CategoryID', 'CategoryName']
✅ Tabla 'products' creada con éxito. Columnas: ['ProductID', 'ProductNumber', 'ProductName', 'ModelName', 'MakeFlag', 'StandardCost', 'ListPrice', 'SubCategoryID']
✅ Tabla 'vendors' creada con éxito. Columnas: ['VendorID', 'VendorName', 'AccountNumber', 'CreditRating', 'ActiveFlag']

In [15]:
query = "SELECT name FROM sqlite_master WHERE type='table';"
tables = pd.read_sql_query(query, engine)
print("Tablas disponibles:")
display(tables)

Tablas disponibles:

                name
0          customers
1          employees
2             orders
3  productcategories
4           products
5            vendors

from matplotlib import pyplot as plt
import seaborn as sns
tables.groupby('name').size().plot(kind='barh', color=sns.palettes.mpl_palette('Dark2'))
plt.gca().spines[['top', 'right',]].set_visible(False)

In [18]:
query = """
SELECT *
FROM employees LIMIT 2;
"""
result = pd.read_sql_query(query, engine)
display(result)

,EmployeeID,ManagerID,FirstName,LastName,FullName,JobTitle,OrganizationLevel,MaritalStatus,Gender,Territory,Country,Group
0,274,NaN,Stephen,Jiang,Stephen Jiang,North American Sales Manager,2,M,M,None,None,None
1,275,274.0,Michael,Blythe,Michael Blythe,Sales Representative,3,S,M,Northeast,US,North America

In [24]:
query = """
SELECT *
FROM orders LIMIT 8;
"""
result = pd.read_sql_query(query, engine)
display(result)

,SalesOrderID,SalesOrderDetailID,OrderDate,DueDate,ShipDate,EmployeeID,CustomerID,SubTotal,TaxAmt,Freight,TotalDue,ProductID,OrderQty,UnitPrice,UnitPriceDiscount,LineTotal
0,43659,1,5/31/2011,6/12/2011,6/7/2011,279,1045,20565.6206,1971.5149,616.0984,23153.2339,776,1,2024.9940,0.0,2024.9940
1,43659,2,5/31/2011,6/12/2011,6/7/2011,279,1045,20565.6206,1971.5149,616.0984,23153.2339,777,3,2024.9940,0.0,6074.9820
2,43659,3,5/31/2011,6/12/2011,6/7/2011,279,1045,20565.6206,1971.5149,616.0984,23153.2339,778,1,2024.9940,0.0,2024.9940
3,43659,4,5/31/2011,6/12/2011,6/7/2011,279,1045,20565.6206,1971.5149,616.0984,23153.2339,771,1,2039.9940,0.0,2039.9940
4,43659,5,5/31/2011,6/12/2011,6/7/2011,279,1045,20565.6206,1971.5149,616.0984,23153.2339,772,1,2039.9940,0.0,2039.9940
5,43659,6,5/31/2011,6/12/2011,6/7/2011,279,1045,20565.6206,1971.5149,616.0984,23153.2339,773,2,2039.9940,0.0,4079.9880
6,43659,7,5/31/2011,6/12/2011,6/7/2011,279,1045,20565.6206,1971.5149,616.0984,23153.2339,774,1,2039.9940,0.0,2039.9940
7,43659,8,5/31/2011,6/12/2011,6/7/2011,279,1045,20565.6206,1971.5149,616.0984,23153.2339,714,3,28.8404,0.0,86.5212

In [25]:
query = """
SELECT *
FROM orders
Group by EmployeeID;
"""
result = pd.read_sql_query(query, engine)
display(result)

,SalesOrderID,SalesOrderDetailID,OrderDate,DueDate,ShipDate,EmployeeID,CustomerID,SubTotal,TaxAmt,Freight,TotalDue,ProductID,OrderQty,UnitPrice,UnitPriceDiscount,LineTotal
0,43849,535,7/1/2011,7/13/2011,7/8/2011,274,1031,20544.7015,1969.9765,615.6177,23130.2957,776,2,2024.9940,0.0,4049.9880
1,43670,111,5/31/2011,6/12/2011,6/7/2011,275,487,6122.0820,587.5603,183.6126,6893.2549,710,1,5.7000,0.0,5.7000
2,43663,52,5/31/2011,6/12/2011,6/7/2011,276,483,419.4589,40.2681,12.5838,472.3108,760,1,419.4589,0.0,419.4589
3,43667,77,5/31/2011,6/12/2011,6/7/2011,277,1373,6107.0820,586.1203,183.1626,6876.3649,710,3,5.7000,0.0,17.1000
4,43677,155,5/31/2011,6/12/2011,6/7/2011,278,1043,7793.1108,747.1011,233.4691,8773.6810,715,3,28.8404,0.0,86.5212
5,43659,1,5/31/2011,6/12/2011,6/7/2011,279,1045,20565.6206,1971.5149,616.0984,23153.2339,776,1,2024.9940,0.0,2024.9940
6,43664,53,5/31/2011,6/12/2011,6/7/2011,280,1205,24432.6088,2344.9921,732.8100,27510.4109,772,1,2039.9940,0.0,2039.9940
7,43678,167,5/31/2011,6/12/2011,6/7/2011,281,1183,9799.9243,942.0740,294.3981,11036.3964,760,1,419.4589,0.0,419.4589
8,43661,15,5/31/2011,6/12/2011,6/7/2011,282,851,32726.4786,3153.7696,985.5530,36865.8012,745,1,809.7600,0.0,809.7600
9,43665,61,5/31/2011,6/12/2011,6/7/2011,283,517,14352.7713,1375.9427,429.9821,16158.6961,711,2,20.1865,0.0,40.3730
10,47982,20236,9/30/2012,10/12/2012,10/7/2012,284,1411,67.5490,6.6648,2.0828,76.2966,809,2,33.7745,0.0,67.5490
11,53485,47717,7/31/2013,8/12/2013,8/7/2013,285,299,57771.7641,6201.0736,1937.8355,65910.6732,916,2,31.5840,0.0,63.1680
12,51087,35684,5/30/2013,6/11/2013,6/6/2013,286,563,2288.7072,329.5738,102.9918,2721.2728,954,3,953.6280,0.2,2288.7072
13,46982,13744,6/30/2012,7/12/2012,7/7/2012,287,627,65.6018,6.4727,2.0227,74.0972,810,1,65.6018,0.0,65.6018
14,51098,35944,5/30/2013,6/11/2013,6/6/2013,288,887,1344.5880,129.0804,40.3376,1514.0060,801,2,672.2940,0.0,1344.5880
15,46607,10722,5/30/2012,6/11/2012,6/6/2012,289,1417,120182.1850,11751.9938,3672.4981,135606.6769,790,4,1466.0100,0.0,5864.0400
16,46623,11110,5/30/2012,6/11/2012,6/6/2012,290,1985,2278.1544,223.0499,69.7031,2570.9074,785,1,647.9940,0.0,647.9940

In [27]:
query = """
SELECT
e.EmployeeID,
e.FullName,
SUM(o.LineTotal) AS VentaTotal
FROM orders o
JOIN employees e ON o.EmployeeID = e.EmployeeID
GROUP BY e.EmployeeID
ORDER BY VentaTotal DESC;
"""
result = pd.read_sql_query(query, engine)
display(result)

    EmployeeID                  FullName    VentaTotal
0          276            Linda Mitchell  1.036701e+07
1          277            Jillian Carson  1.006580e+07
2          275            Michael Blythe  9.293903e+06
3          289                   Jae Pak  8.503339e+06
4          279               Tsvi Reiter  7.171013e+06
5          281                   Shu Ito  6.427006e+06
6          282              José Saraiva  5.926418e+06
7          290  Ranjit Varkey Chudukatil  4.509889e+06
8          283            David Campbell  3.729945e+06
9          278            Garrett Vargas  3.609447e+06
10         280       Pamela Ansman-Wolfe  3.325103e+06
11         284          Tete Mensa-Annan  2.312546e+06
12         288             Rachel Valdez  1.827067e+06
13         286             Lynn Tsoflias  1.421811e+06
14         274             Stephen Jiang  1.092124e+06
15         287               Amy Alberts  7.327592e+05
16         285                Syed Abbas  1.725245e+05